In [1]:
import pandas as pd
import numpy as np

In [2]:
Data = pd.read_excel("/Ola July Data.xlsx")

In [36]:
Data.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehical Image'],
      dtype='object')

In [3]:
Checking_Data = Data.head
print(Checking_Data)

<bound method NDFrame.head of                       Date      Time     Booking_ID        Booking_Status  \
0      2024-07-26 14:00:00  14:00:00  CNR7153255142    Canceled by Driver
1      2024-07-25 22:20:00  22:20:00  CNR2940424040               Success
2      2024-07-30 19:59:00  19:59:00  CNR2982357879               Success
3      2024-07-22 03:15:00  03:15:00  CNR2395710036  Canceled by Customer
4      2024-07-02 09:02:00  09:02:00  CNR1797421769               Success
...                    ...       ...            ...                   ...
103019 2024-07-31 09:06:00  09:06:00  CNR9488489435               Success
103020 2024-07-31 15:12:00  15:12:00  CNR3151743100               Success
103021 2024-07-31 13:59:00  13:59:00  CNR1286151233               Success
103022 2024-07-31 14:56:00  14:56:00  CNR2027162035               Success
103023 2024-07-31 13:57:00  13:57:00  CNR9770709721               Success

       Customer_ID Vehicle_Type    Pickup_Location  Drop_Location  V_TAT  \
0        CID713523  Prime Sedan        Tumkur Road       RT Nagar    NaN
1        CID225428         Bike        Magadi Road        Varthur  203.0
2        CID270156    Prime SUV      Sahakar Nagar        Varthur  238.0
3        CID581320        eBike         HSR Layout    Vijayanagar    NaN
4        CID939555         Mini        Rajajinagar    Chamarajpet  252.0
...            ...          ...                ...            ...    ...
103019   CID371654   Prime Plus      Richmond Town        Varthur  245.0
103020   CID334158         Auto        Vijayanagar  Richmond Town   84.0
103021   CID113188    Prime SUV  Bannerghatta Road       JP Nagar   35.0
103022   CID118301        eBike        Indiranagar    Magadi Road  210.0
103023   CID217959         Auto             Ulsoor         Hennur  175.0

        C_TAT                    Canceled_Rides_by_Customer  \
0         NaN                                           NaN
1        30.0                                           NaN
2       130.0                                           NaN
3         NaN  Driver is not moving towards pickup location
4        80.0                                           NaN
...       ...                                           ...
103019   35.0                                           NaN
103020  145.0                                           NaN
103021   75.0                                           NaN
103022  140.0                                           NaN
103023  125.0                                           NaN

            Canceled_Rides_by_Driver Incomplete_Rides Incomplete_Rides_Reason  \
0       Personal & Car related issue              NaN                     NaN
1                                NaN               No                     NaN
2                                NaN               No                     NaN
3                                NaN              NaN                     NaN
4                                NaN               No                     NaN
...                              ...              ...                     ...
103019                           NaN               No                     NaN
103020                           NaN               No                     NaN
103021                           NaN               No                     NaN
103022                           NaN               No                     NaN
103023                           NaN               No                     NaN

        Booking_Value Payment_Method  Ride_Distance  Driver_Ratings  \
0                 444            NaN              0             NaN
1                 158           Cash             13             4.1
2                 386            UPI             40             4.2
3                 384            NaN              0             NaN
4                 822    Credit Card             45             4.0
...               ...            ...            ...             ...
103019            111           Cash             41             3.6
103020           1097            UPI             17             4.3
103021           2201           Cash             37             3.6
103022            267            UPI             47             3.4
103023            462            UPI              3             4.8

        Customer_Rating                                      Vehical Image
0                   NaN  https://cdn-icons-png.flaticon.com/128/14183/1...
1                   4.0  https://cdn-icons-png.flaticon.com/128/9983/99...
2                   4.8  https://cdn-icons-png.flaticon.com/128/9983/99...
3                   NaN  https://cdn-icons-png.flaticon.com/128/6839/68...
4                   3.0  https://cdn-icons-png.flaticon.com/128/3202/32...
...                 ...                                                ...
103019              3.8  https://cdn-icons-png.flaticon.com/128/11409/1...
103020              3.3  https://cdn-icons-png.flaticon.com/128/16526/1...
103021              3.2  https://cdn-icons-png.flaticon.com/128/9983/99...
103022              3.1  https://cdn-icons-png.flaticon.com/128/6839/68...
103023              4.4  https://cdn-icons-png.flaticon.com/128/16526/1...

[103024 rows x 20 columns]>

In [24]:
# Retrieve all successful bookings
Successful_Bookings = Data[Data['Booking_Status'] =="Success"]

#Count of Sucessfull Booking
Total_Count = len(Successful_Bookings)
print('Total_Successful_Bookings :',Total_Count)

Total_Successful_Bookings : 63967

In [5]:
#Find the average ride distance for each vehicle type
Average_Ride_Distance = Data.groupby('Vehicle_Type')['Ride_Distance'].mean()
print(Average_Ride_Distance)

Vehicle_Type
Auto            6.238089
Bike           15.533079
Mini           15.510102
Prime Plus     15.447474
Prime SUV      15.274514
Prime Sedan    15.764939
eBike          15.580589
Name: Ride_Distance, dtype: float64

In [26]:
# Get the total number of cancelled rides by customers
Cancelled_Rides_by_Customer = Data[Data['Booking_Status'] == 'Canceled by Customer']
Total_Cancelled_Rides = len(Cancelled_Rides_by_Customer)
print('Total_Cancelled_Rides :',Total_Cancelled_Rides)

Total_Cancelled_Rides : 10499

In [7]:
# List the top 5 customers who booked the highest number of rides
Top_5_Customers = Data.groupby('Customer_ID')['Booking_Value'].sum().sort_values(ascending=False).head(5)
print(Top_5_Customers)

Customer_ID
CID785112    8025
CID308763    6281
CID734557    6177
CID353074    6110
CID836942    6019
Name: Booking_Value, dtype: int64

In [21]:
# Get the number of rides cancelled by drivers due to personal and car-related issues
Cancelled_Rides_by_Drivers = Data[Data['Canceled_Rides_by_Driver'] == 'Personal & Car related issue']
Total_Cancelled_Rides = len(Cancelled_Rides_by_Drivers)
print('Total_Cancelled_Rides :', Total_Cancelled_Rides)

Total_Cancelled_Rides : 6542

In [11]:
# Find the maximum and minimum driver ratings for Prime Sedan bookings:
Prime_Sedan_Ratings = Data[Data['Vehicle_Type'] == 'Prime Sedan']
Max_Rating = Prime_Sedan_Ratings['Driver_Ratings'].max()
Min_Rating = Prime_Sedan_Ratings['Driver_Ratings'].min()
print("Maximum Rating:", Max_Rating)
print("Minimum Rating:", Min_Rating)

Maximum Rating: 5.0
Minimum Rating: 3.0

In [13]:
# Retrieve all rides where payment was made using UPI:
UPI_Payments = Data[Data['Payment_Method'] == 'UPI']
print(UPI_Payments)

                      Date      Time     Booking_ID Booking_Status  \
2      2024-07-30 19:59:00  19:59:00  CNR2982357879        Success
5      2024-07-13 04:42:00  04:42:00  CNR8787177882        Success
12     2024-07-27 13:18:00  13:18:00  CNR4524472111        Success
14     2024-07-16 09:54:00  09:54:00  CNR8181602032        Success
15     2024-07-02 10:25:00  10:25:00  CNR8090918544        Success
...                    ...       ...            ...            ...
103017 2024-07-31 19:34:00  19:34:00  CNR4870774895        Success
103018 2024-07-31 03:00:00  03:00:00  CNR9738039746        Success
103020 2024-07-31 15:12:00  15:12:00  CNR3151743100        Success
103022 2024-07-31 14:56:00  14:56:00  CNR2027162035        Success
103023 2024-07-31 13:57:00  13:57:00  CNR9770709721        Success

       Customer_ID Vehicle_Type Pickup_Location  Drop_Location  V_TAT  C_TAT  \
2        CID270156    Prime SUV   Sahakar Nagar        Varthur  238.0  130.0
5        CID802429         Mini        Kadugodi    Vijayanagar  231.0   90.0
12       CID540929         Auto        Cox Town      Yelahanka  126.0   35.0
14       CID167642         Bike     Indiranagar        MG Road   70.0   95.0
15       CID640151         Bike     Magadi Road     HSR Layout  126.0   95.0
...            ...          ...             ...            ...    ...    ...
103017   CID266336  Prime Sedan    Marathahalli       Cox Town  189.0   30.0
103018   CID922711        eBike        Chickpet       RT Nagar   42.0  135.0
103020   CID334158         Auto     Vijayanagar  Richmond Town   84.0  145.0
103022   CID118301        eBike     Indiranagar    Magadi Road  210.0  140.0
103023   CID217959         Auto          Ulsoor         Hennur  175.0  125.0

       Canceled_Rides_by_Customer Canceled_Rides_by_Driver Incomplete_Rides  \
2                             NaN                      NaN               No
5                             NaN                      NaN               No
12                            NaN                      NaN               No
14                            NaN                      NaN               No
15                            NaN                      NaN               No
...                           ...                      ...              ...
103017                        NaN                      NaN               No
103018                        NaN                      NaN               No
103020                        NaN                      NaN               No
103022                        NaN                      NaN               No
103023                        NaN                      NaN               No

       Incomplete_Rides_Reason  Booking_Value Payment_Method  Ride_Distance  \
2                          NaN            386            UPI             40
5                          NaN            173            UPI             41
12                         NaN            330            UPI              8
14                         NaN            378            UPI             18
15                         NaN            343            UPI             23
...                        ...            ...            ...            ...
103017                     NaN            280            UPI             38
103018                     NaN            310            UPI              7
103020                     NaN           1097            UPI             17
103022                     NaN            267            UPI             47
103023                     NaN            462            UPI              3

        Driver_Ratings  Customer_Rating  \
2                  4.2              4.8
5                  3.4              4.6
12                 3.0              4.8
14                 4.8              4.1
15                 3.7              3.6
...                ...              ...
103017             3.4              4.1
103018             3.8              3.3
103020             4.3              3.3
103022             3.4              3.1
103023             4.8              4.4

                                            Vehical Image
2       https://cdn-icons-png.flaticon.com/128/9983/99...
5       https://cdn-icons-png.flaticon.com/128/3202/32...
12      https://cdn-icons-png.flaticon.com/128/16526/1...
14      https://cdn-icons-png.flaticon.com/128/9983/99...
15      https://cdn-icons-png.flaticon.com/128/9983/99...
...                                                   ...
103017  https://cdn-icons-png.flaticon.com/128/14183/1...
103018  https://cdn-icons-png.flaticon.com/128/6839/68...
103020  https://cdn-icons-png.flaticon.com/128/16526/1...
103022  https://cdn-icons-png.flaticon.com/128/6839/68...
103023  https://cdn-icons-png.flaticon.com/128/16526/1...

[25881 rows x 20 columns]

In [17]:
# To display in Table format.
from IPython.display import display
display(UPI_Payments)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehical Image
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
5,2024-07-13 04:42:00,04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NaN,NaN,No,NaN,173,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...
12,2024-07-27 13:18:00,13:18:00,CNR4524472111,Success,CID540929,Auto,Cox Town,Yelahanka,126.0,35.0,NaN,NaN,No,NaN,330,UPI,8,3.0,4.8,https://cdn-icons-png.flaticon.com/128/16526/1...
14,2024-07-16 09:54:00,09:54:00,CNR8181602032,Success,CID167642,Bike,Indiranagar,MG Road,70.0,95.0,NaN,NaN,No,NaN,378,UPI,18,4.8,4.1,https://cdn-icons-png.flaticon.com/128/9983/99...
15,2024-07-02 10:25:00,10:25:00,CNR8090918544,Success,CID640151,Bike,Magadi Road,HSR Layout,126.0,95.0,NaN,NaN,No,NaN,343,UPI,23,3.7,3.6,https://cdn-icons-png.flaticon.com/128/9983/99...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103017,2024-07-31 19:34:00,19:34:00,CNR4870774895,Success,CID266336,Prime Sedan,Marathahalli,Cox Town,189.0,30.0,NaN,NaN,No,NaN,280,UPI,38,3.4,4.1,https://cdn-icons-png.flaticon.com/128/14183/1...
103018,2024-07-31 03:00:00,03:00:00,CNR9738039746,Success,CID922711,eBike,Chickpet,RT Nagar,42.0,135.0,NaN,NaN,No,NaN,310,UPI,7,3.8,3.3,https://cdn-icons-png.flaticon.com/128/6839/68...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [19]:
# Count of total payment done by UPI.
Total_UPI_Count = UPI_Payments.shape[0]
print('Total_UPI_Count :', Total_UPI_Count)

Total_UPI_Count : 25881

In [31]:
# Find the average customer rating per vehicle type:
Average_Customer_Rating = Data.groupby('Vehicle_Type')['Customer_Rating'].mean().round(2)
print(Average_Customer_Rating)

Vehicle_Type
Auto           4.00
Bike           3.99
Mini           4.00
Prime Plus     4.01
Prime SUV      4.00
Prime Sedan    4.00
eBike          3.99
Name: Customer_Rating, dtype: float64

In [35]:
# Calculate the total booking value of rides completed successfully:
Successful_Rides= Data[Data['Booking_Status'] == 'Success']
Total_Booking_Value = Successful_Rides['Booking_Value'].sum()
print('Total Booking Value of Successful Rides :', Total_Booking_Value)

Total Booking Value of Successful Rides : 35080467

In [37]:
# List all incomplete rides along with the reason:
Incomplete_Rides = Data[Data['Incomplete_Rides'] == 'Yes']['Incomplete_Rides_Reason'].value_counts()
print('Incomplete Rides with reason are : ',Incomplete_Rides)

Incomplete Rides with reason are :  Incomplete_Rides_Reason
Customer Demand      1601
Vehicle Breakdown    1591
Other Issue           734
Name: count, dtype: int64